/* -*- C++ -*- */
#ifndef OPENDDS_IDL_GENERATED_DCS_DATATYPESUPPORTIMPL_H
#define OPENDDS_IDL_GENERATED_DCS_DATATYPESUPPORTIMPL_H
#include "DCS_DataC.h"
#include "DCS_DataTypeSupportC.h"
#include "dds/DCPS/DataBlockLockPool.h"
#include "dds/DCPS/DataReaderImpl.h"
#include "dds/DCPS/DataWriterImpl.h"
#include "dds/DCPS/Dynamic_Cached_Allocator_With_Overflow_T.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/SubscriptionInstance.h"
#include "dds/DCPS/TypeSupportImpl.h"
/* Generated by /usr/local/DDS/bin/opendds_idl running on input file DCS_Data.idl */


/* Begin MODULE: DCS */



/* Begin TYPEDEF: OctetSeq */

namespace OpenDDS { namespace DCPS {

bool gen_is_bounded_size(const DCS::OctetSeq& seq);

size_t gen_max_marshaled_size(const DCS::OctetSeq& seq);

size_t gen_find_size(const DCS::OctetSeq& seq);

bool operator<<(Serializer& strm, const DCS::OctetSeq& seq);

bool operator>>(Serializer& strm, DCS::OctetSeq& seq);

}  }


/* End TYPEDEF: OctetSeq */


/* Begin STRUCT: DCS_DataDiff */

namespace OpenDDS { namespace DCPS {

bool gen_is_bounded_size(const DCS::DCS_DataDiff& stru);

size_t gen_max_marshaled_size(const DCS::DCS_DataDiff& stru);

size_t gen_find_size(const DCS::DCS_DataDiff& stru);

bool operator<<(Serializer& strm, const DCS::DCS_DataDiff& stru);

bool operator>>(Serializer& strm, DCS::DCS_DataDiff& stru);

}  }

namespace OpenDDS { namespace DCPS {

bool gen_has_key(const DCS::DCS_DataDiff&);

}  }

namespace DCS {
namespace OpenDDSGenerated {
// This structure supports use of std::map with a key
// defined by one or more #pragma DCPS_DATA_KEY lines.
struct  DCS_DataDiff_KeyLessThan {
  bool operator()(const DCS::DCS_DataDiff& v1, const DCS::DCS_DataDiff& v2) const
  {
#ifndef OPENDDS_GCC33
    using ::operator<; // TAO::String_Manager's operator< is in global NS
#endif
    if (v1.data_file_id < v2.data_file_id) return true;
    if (v2.data_file_id < v1.data_file_id) return false;
    return false;
  }
};
}
}
namespace DCS {
/** Servant for TypeSuport interface of DCS_DataDiff data type.
 *
 * See the DDS specification, OMG formal/04-12-02, for a description of
 * this interface.
 *
 */
class  DCS_DataDiffTypeSupportImpl
  : public virtual OpenDDS::DCPS::LocalObject<DCS_DataDiffTypeSupport>
  , public virtual OpenDDS::DCPS::TypeSupportImpl
{
public:

  //Constructor
  DCS_DataDiffTypeSupportImpl ();

  //Destructor
  virtual ~DCS_DataDiffTypeSupportImpl ();

  virtual
  DDS::ReturnCode_t register_type (::DDS::DomainParticipant_ptr participant,
                                   const char * type_name)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual char * get_type_name () ACE_THROW_SPEC ((CORBA::SystemException));

  virtual ::DDS::DataWriter_ptr create_datawriter ()
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual ::DDS::DataReader_ptr create_datareader ()
    ACE_THROW_SPEC ((CORBA::SystemException));

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual ::DDS::DataReader_ptr create_multitopic_datareader()
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType();
#endif


private:
  CORBA::String_var type_name_;
};

/** Servant for DataWriter interface of the DCS_DataDiff data type.
 *
 * See the DDS specification, OMG formal/04-12-02, for a description of
 * this interface.
 */
class  DCS_DataDiffDataWriterImpl
  : public virtual OpenDDS::DCPS::LocalObject<DCS_DataDiffDataWriter>,
    public virtual OpenDDS::DCPS::DataWriterImpl
{
public:

  typedef std::map<DCS::DCS_DataDiff, DDS::InstanceHandle_t,
      OpenDDSGenerated::DCS_DataDiff_KeyLessThan> InstanceMap;
  typedef ::OpenDDS::DCPS::Dynamic_Cached_Allocator_With_Overflow<ACE_Null_Mutex>  DataAllocator;

  //Constructor
  DCS_DataDiffDataWriterImpl (void);

  //Destructor
  virtual ~DCS_DataDiffDataWriterImpl (void);

  virtual DDS::InstanceHandle_t register_instance (
      const ::DCS::DCS_DataDiff & instance)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::DCS::DCS_DataDiff & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual DDS::ReturnCode_t unregister_instance (
      const ::DCS::DCS_DataDiff & instance,
      ::DDS::InstanceHandle_t handle)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::DCS::DCS_DataDiff & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp)
    ACE_THROW_SPEC ((CORBA::SystemException));

  //WARNING: If the handle is non-nil and the instance is not registered
  //         then this operation may cause an access violation.
  //         This lack of safety helps performance.
  virtual DDS::ReturnCode_t write (
      const ::DCS::DCS_DataDiff & instance_data,
      ::DDS::InstanceHandle_t handle)
    ACE_THROW_SPEC ((CORBA::SystemException));

  //WARNING: If the handle is non-nil and the instance is not registered
  //         then this operation may cause an access violation.
  //         This lack of safety helps performance.
  virtual DDS::ReturnCode_t write_w_timestamp (
      const ::DCS::DCS_DataDiff & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual DDS::ReturnCode_t dispose (
      const ::DCS::DCS_DataDiff & instance_data,
      ::DDS::InstanceHandle_t instance_handle)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual DDS::ReturnCode_t dispose_w_timestamp (
      const ::DCS::DCS_DataDiff & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual DDS::ReturnCode_t get_key_value (
      ::DCS::DCS_DataDiff & key_holder,
      ::DDS::InstanceHandle_t handle)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DCS::DCS_DataDiff & instance_data)
    ACE_THROW_SPEC ((CORBA::SystemException));

  /**
   * Initialize the DataWriter object.
   * Called as part of create_datawriter.
   */
  virtual void init (
        ::DDS::Topic_ptr                       topic,
        OpenDDS::DCPS::TopicImpl*              topic_servant,
        const ::DDS::DataWriterQos &           qos,
        ::DDS::DataWriterListener_ptr          a_listener,
        const ::DDS::StatusMask &              mask,
        OpenDDS::DCPS::DomainParticipantImpl*  participant_servant,
        OpenDDS::DCPS::PublisherImpl*          publisher_servant,
        ::DDS::DataWriter_ptr                  dw_objref,
        ::OpenDDS::DCPS::DataWriterRemote_ptr  dw_remote_objref
      )
    ACE_THROW_SPEC ((CORBA::SystemException));

  /**
   * Do parts of enable specific to the datatype.
   * Called by DataWriterImpl::enable().
   */
  virtual ::DDS::ReturnCode_t enable_specific ()
    ACE_THROW_SPEC ((CORBA::SystemException));

  /**
   * The framework has completed its part of unregistering the
   * given instance.
   */
  virtual void unregistered(::DDS::InstanceHandle_t instance_handle);

  /**
   * Accessor to the marshalled data sample allocator.
   */
  ACE_INLINE
  DataAllocator* data_allocator () const  {
    return data_allocator_;
  };

private:

  /**
   * Serialize the instance data.
   *
   * @param instance_data The data to serialize.
   * @param for_write If 1 use the fast allocator; otherwise use the heap.
   * @return returns the serialized data.
   */
  ACE_Message_Block* dds_marshal(
    const ::DCS::DCS_DataDiff& instance_data,
    int  for_write = 1);

  /**
   * Find the instance handle for the given instance_data using
   * the data type's key(s).  If the instance does not already exist
   * create a new instance handle for it.
   */
  ::DDS::ReturnCode_t get_or_create_instance_handle(
    DDS::InstanceHandle_t& handle,
    const ::DCS::DCS_DataDiff& instance_data,
    const ::DDS::Time_t & source_timestamp);

   InstanceMap  instance_map_;
   size_t       marshaled_size_;
   // The lock pool will be thread safe because
   // only one write call is allowed at a time.
   DataBlockLockPool*  db_lock_pool_;
   DataAllocator* data_allocator_;
   ::OpenDDS::DCPS::MessageBlockAllocator* mb_allocator_;
   ::OpenDDS::DCPS::DataBlockAllocator*    db_allocator_;
};

/** Servant for DataReader interface of DCS_DataDiff data type.
 *
 * See the DDS specification, OMG formal/04-12-02, for a description of
 * this interface.
 *
 */
class  DCS_DataDiffDataReaderImpl
  : public virtual OpenDDS::DCPS::LocalObject<DCS_DataDiffDataReader>,
    public virtual OpenDDS::DCPS::DataReaderImpl
{
public:

  typedef std::map<DCS::DCS_DataDiff, DDS::InstanceHandle_t,
      OpenDDSGenerated::DCS_DataDiff_KeyLessThan> InstanceMap;
  typedef ::OpenDDS::DCPS::Cached_Allocator_With_Overflow<DCS::DCS_DataDiff, ACE_Null_Mutex>  DataAllocator;
  typedef DCS_DataDiffDataReader Interface;

  //Constructor
  DCS_DataDiffDataReaderImpl (void);

  //Destructor
  virtual ~DCS_DataDiffDataReaderImpl (void);

  virtual DDS::ReturnCode_t delete_contained_entities ()
    ACE_THROW_SPEC ((CORBA::SystemException));

  /**
   * Do parts of enable specific to the datatype.
   * Called by DataReaderImpl::enable().
   */
  virtual ::DDS::ReturnCode_t enable_specific ()
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual DDS::ReturnCode_t read (
      ::DCS::DCS_DataDiffSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual DDS::ReturnCode_t take (
      ::DCS::DCS_DataDiffSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual ::DDS::ReturnCode_t read_w_condition (
      ::DCS::DCS_DataDiffSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual ::DDS::ReturnCode_t take_w_condition (
      ::DCS::DCS_DataDiffSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual DDS::ReturnCode_t read_next_sample (
      ::DCS::DCS_DataDiff & received_data,
      ::DDS::SampleInfo & sample_info)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual DDS::ReturnCode_t take_next_sample (
      ::DCS::DCS_DataDiff & received_data,
      ::DDS::SampleInfo & sample_info)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual DDS::ReturnCode_t read_instance (
      ::DCS::DCS_DataDiffSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual DDS::ReturnCode_t take_instance (
      ::DCS::DCS_DataDiffSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual DDS::ReturnCode_t read_next_instance (
      ::DCS::DCS_DataDiffSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual DDS::ReturnCode_t take_next_instance (
      ::DCS::DCS_DataDiffSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::DCS::DCS_DataDiffSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::DCS::DCS_DataDiffSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual DDS::ReturnCode_t return_loan (
      ::DCS::DCS_DataDiffSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual DDS::ReturnCode_t get_key_value (
      ::DCS::DCS_DataDiff & key_holder,
      ::DDS::InstanceHandle_t handle)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DCS::DCS_DataDiff & instance_data)
    ACE_THROW_SPEC ((CORBA::SystemException));

  virtual DDS::ReturnCode_t auto_return_loan(void* seq);

  void release_loan (::DCS::DCS_DataDiffSeq & received_data);

  void dec_ref_data_element(::OpenDDS::DCPS::ReceivedDataElement* r);

  virtual void delete_instance_map (void* map);

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  bool contains_sample_filtered(DDS::SampleStateMask sample_states,
                                DDS::ViewStateMask view_states,
                                DDS::InstanceStateMask instance_states,
                                const OpenDDS::DCPS::FilterEvaluator& evaluator,
                                const DDS::StringSeq& params);

  DDS::ReturnCode_t read_generic(
    OpenDDS::DCPS::DataReaderImpl::GenericBundle& gen,
    DDS::SampleStateMask sample_states, DDS::ViewStateMask view_states,
    DDS::InstanceStateMask instance_states);

  DDS::InstanceHandle_t lookup_instance_generic(const void* data);

  DDS::ReturnCode_t read_instance_generic(void*& data,
    DDS::SampleInfo& info, DDS::InstanceHandle_t instance,
    DDS::SampleStateMask sample_states, DDS::ViewStateMask view_states,
    DDS::InstanceStateMask instance_states);

  DDS::ReturnCode_t read_next_instance_generic(void*& data,
    DDS::SampleInfo& info, DDS::InstanceHandle_t previous_instance,
    DDS::SampleStateMask sample_states, DDS::ViewStateMask view_states,
    DDS::InstanceStateMask instance_states);

  DDS::InstanceHandle_t store_synthetic_data(const DCS::DCS_DataDiff& sample,
                                             DDS::ViewStateKind view);

  void set_instance_state(DDS::InstanceHandle_t instance,
                          DDS::InstanceStateKind state);
#endif

  virtual void lookup_instance(const OpenDDS::DCPS::ReceivedDataSample& sample,
                               OpenDDS::DCPS::SubscriptionInstance*& instance);

 protected:

    virtual void dds_demarshal(const OpenDDS::DCPS::ReceivedDataSample& sample,
                               OpenDDS::DCPS::SubscriptionInstance*& instance,
                               bool & just_registered,
                               bool & filtered);

    virtual void dispose(const OpenDDS::DCPS::ReceivedDataSample& sample,
                         OpenDDS::DCPS::SubscriptionInstance*& instance);

    virtual void unregister(const OpenDDS::DCPS::ReceivedDataSample& sample,
                            OpenDDS::DCPS::SubscriptionInstance*& instance);

    //virtual OpenDDS::DCPS::DataReaderRemote_ptr get_datareaderremote_obj_ref ();

    virtual void purge_data(OpenDDS::DCPS::SubscriptionInstance* instance);

    virtual void release_instance_i (::DDS::InstanceHandle_t handle);

  private:

    ::DDS::ReturnCode_t read_i (
      ::DCS::DCS_DataDiffSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states,
      ::DDS::QueryCondition_ptr a_condition
      );

    ::DDS::ReturnCode_t take_i (
      ::DCS::DCS_DataDiffSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states,
      ::DDS::QueryCondition_ptr a_condition
      );

    DDS::ReturnCode_t read_instance_i (
      ::DCS::DCS_DataDiffSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states,
      ::DDS::QueryCondition_ptr a_condition
      );

    DDS::ReturnCode_t take_instance_i (
      ::DCS::DCS_DataDiffSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states,
      ::DDS::QueryCondition_ptr a_condition
      );

    DDS::ReturnCode_t read_next_instance_i (
      ::DCS::DCS_DataDiffSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states,
      ::DDS::QueryCondition_ptr a_condition
      );

    DDS::ReturnCode_t take_next_instance_i (
      ::DCS::DCS_DataDiffSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states,
      ::DDS::QueryCondition_ptr a_condition
      );

    void store_instance_data(
         ::DCS::DCS_DataDiff *instance_data,
         const OpenDDS::DCPS::DataSampleHeader& header,
         OpenDDS::DCPS::SubscriptionInstance*& instance_ptr,
         bool & just_registered,
         bool & filtered
         );

    /// common input read* & take* input processing and precondition checks
    ::DDS::ReturnCode_t check_inputs (
        const char* method_name,
        ::DCS::DCS_DataDiffSeq & received_data,
        ::DDS::SampleInfoSeq & info_seq,
        ::CORBA::Long max_samples
        );

   InstanceMap  instance_map_;
   DataAllocator* data_allocator_;
};
}
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct<DCS::DCS_DataDiff>();
}  }

#endif

/* End STRUCT: DCS_DataDiff */

/* End MODULE: DCS */
#endif /* OPENDDS_IDL_GENERATED_DCS_DATATYPESUPPORTIMPL_H */
