// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler v1.6a_p8 ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:135

#ifndef _TAO_IDL_DCS_DATATYPESUPPORTC_H_
#define _TAO_IDL_DCS_DATATYPESUPPORTC_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/UserException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Objref_VarOut_T.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "DCS_DataC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:49

namespace DCS
{
  
  // TAO_IDL - Generated from
  // be/be_visitor_native/native_ch.cpp:55
  
  
  
  typedef ::TAO::DCPS::ZeroCopyDataSeq< DCS::DCS_DataDiff, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> DCS_DataDiffSeq;
  
  
  // TAO_IDL - Generated from
  // be/be_interface.cpp:644

#if !defined (_DCS_DCS_DATADIFFTYPESUPPORT__VAR_OUT_CH_)
#define _DCS_DCS_DATADIFFTYPESUPPORT__VAR_OUT_CH_
  
  class DCS_DataDiffTypeSupport;
  typedef DCS_DataDiffTypeSupport *DCS_DataDiffTypeSupport_ptr;
  
  typedef
    TAO_Objref_Var_T<
        DCS_DataDiffTypeSupport
      >
    DCS_DataDiffTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        DCS_DataDiffTypeSupport
      >
    DCS_DataDiffTypeSupport_out;

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:54

#if !defined (_DCS_DCS_DATADIFFTYPESUPPORT_CH_)
#define _DCS_DCS_DATADIFFTYPESUPPORT_CH_
  
  class  DCS_DataDiffTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  {
  public:
    typedef DCS_DataDiffTypeSupport_ptr _ptr_type;
    typedef DCS_DataDiffTypeSupport_var _var_type;
    typedef DCS_DataDiffTypeSupport_out _out_type;
    
    // The static operations.
    static DCS_DataDiffTypeSupport_ptr _duplicate (DCS_DataDiffTypeSupport_ptr obj);
    
    static void _tao_release (DCS_DataDiffTypeSupport_ptr obj);
    
    static DCS_DataDiffTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static DCS_DataDiffTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static DCS_DataDiffTypeSupport_ptr _nil (void)
    {
      return static_cast<DCS_DataDiffTypeSupport_ptr> (0);
    }
    
    
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t register_type (
        ::DDS::DomainParticipant_ptr participant,
        const char * type_name) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual char * get_type_name (
        void) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:216
    
    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    DCS_DataDiffTypeSupport (void);
    
    virtual ~DCS_DataDiffTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    DCS_DataDiffTypeSupport (const DCS_DataDiffTypeSupport &);
    
    void operator= (const DCS_DataDiffTypeSupport &);
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_interface.cpp:644

#if !defined (_DCS_DCS_DATADIFFDATAWRITER__VAR_OUT_CH_)
#define _DCS_DCS_DATADIFFDATAWRITER__VAR_OUT_CH_
  
  class DCS_DataDiffDataWriter;
  typedef DCS_DataDiffDataWriter *DCS_DataDiffDataWriter_ptr;
  
  typedef
    TAO_Objref_Var_T<
        DCS_DataDiffDataWriter
      >
    DCS_DataDiffDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        DCS_DataDiffDataWriter
      >
    DCS_DataDiffDataWriter_out;

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:54

#if !defined (_DCS_DCS_DATADIFFDATAWRITER_CH_)
#define _DCS_DCS_DATADIFFDATAWRITER_CH_
  
  class  DCS_DataDiffDataWriter
    : public virtual ::DDS::DataWriter
  {
  public:
    typedef DCS_DataDiffDataWriter_ptr _ptr_type;
    typedef DCS_DataDiffDataWriter_var _var_type;
    typedef DCS_DataDiffDataWriter_out _out_type;
    
    // The static operations.
    static DCS_DataDiffDataWriter_ptr _duplicate (DCS_DataDiffDataWriter_ptr obj);
    
    static void _tao_release (DCS_DataDiffDataWriter_ptr obj);
    
    static DCS_DataDiffDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static DCS_DataDiffDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static DCS_DataDiffDataWriter_ptr _nil (void)
    {
      return static_cast<DCS_DataDiffDataWriter_ptr> (0);
    }
    
    
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::InstanceHandle_t register_instance (
        const ::DCS::DCS_DataDiff & instance) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
        const ::DCS::DCS_DataDiff & instance,
        ::DDS::InstanceHandle_t handle,
        const ::DDS::Time_t & timestamp) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t unregister_instance (
        const ::DCS::DCS_DataDiff & instance,
        ::DDS::InstanceHandle_t handle) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
        const ::DCS::DCS_DataDiff & instance,
        ::DDS::InstanceHandle_t handle,
        const ::DDS::Time_t & timestamp) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t write (
        const ::DCS::DCS_DataDiff & instance_data,
        ::DDS::InstanceHandle_t handle) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t write_w_timestamp (
        const ::DCS::DCS_DataDiff & instance_data,
        ::DDS::InstanceHandle_t handle,
        const ::DDS::Time_t & source_timestamp) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t dispose (
        const ::DCS::DCS_DataDiff & instance_data,
        ::DDS::InstanceHandle_t instance_handle) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
        const ::DCS::DCS_DataDiff & instance_data,
        ::DDS::InstanceHandle_t instance_handle,
        const ::DDS::Time_t & source_timestamp) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t get_key_value (
        ::DCS::DCS_DataDiff & key_holder,
        ::DDS::InstanceHandle_t handle) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::InstanceHandle_t lookup_instance (
        const ::DCS::DCS_DataDiff & instance_data) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:216
    
    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    DCS_DataDiffDataWriter (void);
    
    virtual ~DCS_DataDiffDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    DCS_DataDiffDataWriter (const DCS_DataDiffDataWriter &);
    
    void operator= (const DCS_DataDiffDataWriter &);
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_interface.cpp:644

#if !defined (_DCS_DCS_DATADIFFDATAREADER__VAR_OUT_CH_)
#define _DCS_DCS_DATADIFFDATAREADER__VAR_OUT_CH_
  
  class DCS_DataDiffDataReader;
  typedef DCS_DataDiffDataReader *DCS_DataDiffDataReader_ptr;
  
  typedef
    TAO_Objref_Var_T<
        DCS_DataDiffDataReader
      >
    DCS_DataDiffDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        DCS_DataDiffDataReader
      >
    DCS_DataDiffDataReader_out;

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:54

#if !defined (_DCS_DCS_DATADIFFDATAREADER_CH_)
#define _DCS_DCS_DATADIFFDATAREADER_CH_
  
  class  DCS_DataDiffDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  {
  public:
    typedef DCS_DataDiffDataReader_ptr _ptr_type;
    typedef DCS_DataDiffDataReader_var _var_type;
    typedef DCS_DataDiffDataReader_out _out_type;
    
    // The static operations.
    static DCS_DataDiffDataReader_ptr _duplicate (DCS_DataDiffDataReader_ptr obj);
    
    static void _tao_release (DCS_DataDiffDataReader_ptr obj);
    
    static DCS_DataDiffDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static DCS_DataDiffDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static DCS_DataDiffDataReader_ptr _nil (void)
    {
      return static_cast<DCS_DataDiffDataReader_ptr> (0);
    }
    
    
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t read (
        ::DCS::DCS_DataDiffSeq & received_data,
        ::DDS::SampleInfoSeq & info_seq,
        ::CORBA::Long max_samples,
        ::DDS::SampleStateMask sample_states,
        ::DDS::ViewStateMask view_states,
        ::DDS::InstanceStateMask instance_states) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t take (
        ::DCS::DCS_DataDiffSeq & received_data,
        ::DDS::SampleInfoSeq & info_seq,
        ::CORBA::Long max_samples,
        ::DDS::SampleStateMask sample_states,
        ::DDS::ViewStateMask view_states,
        ::DDS::InstanceStateMask instance_states) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t read_w_condition (
        ::DCS::DCS_DataDiffSeq & data_values,
        ::DDS::SampleInfoSeq & sample_infos,
        ::CORBA::Long max_samples,
        ::DDS::ReadCondition_ptr a_condition) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t take_w_condition (
        ::DCS::DCS_DataDiffSeq & data_values,
        ::DDS::SampleInfoSeq & sample_infos,
        ::CORBA::Long max_samples,
        ::DDS::ReadCondition_ptr a_condition) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t read_next_sample (
        ::DCS::DCS_DataDiff & received_data,
        ::DDS::SampleInfo & sample_info) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t take_next_sample (
        ::DCS::DCS_DataDiff & received_data,
        ::DDS::SampleInfo & sample_info) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t read_instance (
        ::DCS::DCS_DataDiffSeq & received_data,
        ::DDS::SampleInfoSeq & info_seq,
        ::CORBA::Long max_samples,
        ::DDS::InstanceHandle_t a_handle,
        ::DDS::SampleStateMask sample_states,
        ::DDS::ViewStateMask view_states,
        ::DDS::InstanceStateMask instance_states) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t take_instance (
        ::DCS::DCS_DataDiffSeq & received_data,
        ::DDS::SampleInfoSeq & info_seq,
        ::CORBA::Long max_samples,
        ::DDS::InstanceHandle_t a_handle,
        ::DDS::SampleStateMask sample_states,
        ::DDS::ViewStateMask view_states,
        ::DDS::InstanceStateMask instance_states) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t read_next_instance (
        ::DCS::DCS_DataDiffSeq & received_data,
        ::DDS::SampleInfoSeq & info_seq,
        ::CORBA::Long max_samples,
        ::DDS::InstanceHandle_t a_handle,
        ::DDS::SampleStateMask sample_states,
        ::DDS::ViewStateMask view_states,
        ::DDS::InstanceStateMask instance_states) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t take_next_instance (
        ::DCS::DCS_DataDiffSeq & received_data,
        ::DDS::SampleInfoSeq & info_seq,
        ::CORBA::Long max_samples,
        ::DDS::InstanceHandle_t a_handle,
        ::DDS::SampleStateMask sample_states,
        ::DDS::ViewStateMask view_states,
        ::DDS::InstanceStateMask instance_states) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
        ::DCS::DCS_DataDiffSeq & data_values,
        ::DDS::SampleInfoSeq & sample_infos,
        ::CORBA::Long max_samples,
        ::DDS::InstanceHandle_t previous_handle,
        ::DDS::ReadCondition_ptr a_condition) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
        ::DCS::DCS_DataDiffSeq & data_values,
        ::DDS::SampleInfoSeq & sample_infos,
        ::CORBA::Long max_samples,
        ::DDS::InstanceHandle_t previous_handle,
        ::DDS::ReadCondition_ptr a_condition) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t return_loan (
        ::DCS::DCS_DataDiffSeq & received_data,
        ::DDS::SampleInfoSeq & info_seq) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::ReturnCode_t get_key_value (
        ::DCS::DCS_DataDiff & key_holder,
        ::DDS::InstanceHandle_t handle) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual ::DDS::InstanceHandle_t lookup_instance (
        const ::DCS::DCS_DataDiff & instance_data) = 0;
    
    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:216
    
    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    DCS_DataDiffDataReader (void);
    
    virtual ~DCS_DataDiffDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    DCS_DataDiffDataReader (const DCS_DataDiffDataReader &);
    
    void operator= (const DCS_DataDiffDataReader &);
  };

#endif /* end #if !defined */

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:78

} // module DCS

// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:64

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_DCS_DCS_DATADIFFTYPESUPPORT__TRAITS_)
#define _DCS_DCS_DATADIFFTYPESUPPORT__TRAITS_
  
  template<>
  struct  Objref_Traits< ::DCS::DCS_DataDiffTypeSupport>
  {
    static ::DCS::DCS_DataDiffTypeSupport_ptr duplicate (
        ::DCS::DCS_DataDiffTypeSupport_ptr p
      );
    static void release (
        ::DCS::DCS_DataDiffTypeSupport_ptr p
      );
    static ::DCS::DCS_DataDiffTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DCS::DCS_DataDiffTypeSupport_ptr p,
        TAO_OutputCDR & cdr
      );
  };

#endif /* end #if !defined */

#if !defined (_DCS_DCS_DATADIFFDATAWRITER__TRAITS_)
#define _DCS_DCS_DATADIFFDATAWRITER__TRAITS_
  
  template<>
  struct  Objref_Traits< ::DCS::DCS_DataDiffDataWriter>
  {
    static ::DCS::DCS_DataDiffDataWriter_ptr duplicate (
        ::DCS::DCS_DataDiffDataWriter_ptr p
      );
    static void release (
        ::DCS::DCS_DataDiffDataWriter_ptr p
      );
    static ::DCS::DCS_DataDiffDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DCS::DCS_DataDiffDataWriter_ptr p,
        TAO_OutputCDR & cdr
      );
  };

#endif /* end #if !defined */

#if !defined (_DCS_DCS_DATADIFFDATAREADER__TRAITS_)
#define _DCS_DCS_DATADIFFDATAREADER__TRAITS_
  
  template<>
  struct  Objref_Traits< ::DCS::DCS_DataDiffDataReader>
  {
    static ::DCS::DCS_DataDiffDataReader_ptr duplicate (
        ::DCS::DCS_DataDiffDataReader_ptr p
      );
    static void release (
        ::DCS::DCS_DataDiffDataReader_ptr p
      );
    static ::DCS::DCS_DataDiffDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DCS::DCS_DataDiffDataReader_ptr p,
        TAO_OutputCDR & cdr
      );
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1228
#if defined (__ACE_INLINE__)
#include "DCS_DataTypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */


