// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler v1.6a_p8 ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:135

#ifndef _TAO_IDL_DCS_DATAC_H_
#define _TAO_IDL_DCS_DATAC_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include /**/ "tao/Versioned_Namespace.h"

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:49

namespace DCS
{
  
  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:107

#if !defined (_DCS_OCTETSEQ_CH_)
#define _DCS_OCTETSEQ_CH_
  
  class OctetSeq;
  
  typedef
    TAO_FixedSeq_Var_T<
        OctetSeq
      >
    OctetSeq_var;
  
  typedef
    TAO_Seq_Out_T<
        OctetSeq
      >
    OctetSeq_out;
  
  class  OctetSeq
    : public
        TAO::unbounded_value_sequence<
            ::CORBA::Octet
          >
  {
  public:
    OctetSeq (void);
    OctetSeq ( ::CORBA::ULong max);
    OctetSeq (
        ::CORBA::ULong max,
        ::CORBA::ULong length,
        ::CORBA::Octet* buffer, 
        ::CORBA::Boolean release = false
      );
    OctetSeq (const OctetSeq &);
    virtual ~OctetSeq (void);
    
    typedef OctetSeq_var _var_type;
    typedef OctetSeq_out _out_type;
    
    

#if (TAO_NO_COPY_OCTET_SEQUENCES == 1)
    OctetSeq (
        ::CORBA::ULong length,
        const ACE_Message_Block* mb
      )
      : TAO::unbounded_value_sequence< ::CORBA::Octet> (length, mb) {}
#endif /* TAO_NO_COPY_OCTET_SEQUENCE == 1 */
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:269
  
  struct DCS_DataDiff;
  
  typedef
    TAO_Var_Var_T<
        DCS_DataDiff
      >
    DCS_DataDiff_var;
  
  typedef
    TAO_Out_T<
        DCS_DataDiff
      >
    DCS_DataDiff_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:57
  
  struct  DCS_DataDiff
  {
    typedef DCS_DataDiff_var _var_type;
    typedef DCS_DataDiff_out _out_type;
    
    
    ::CORBA::Long data_file_id;
    TAO::String_Manager data_file;
    TAO::String_Manager data_change_source;
    ::CORBA::Long previous_edition;
    ::CORBA::Long new_edition;
    DCS::OctetSeq difference;
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:78

} // module DCS

// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:64

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:71

#if !defined _TAO_CDR_OP_DCS_OctetSeq_H_
#define _TAO_CDR_OP_DCS_OctetSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const DCS::OctetSeq &_tao_sequence
  );
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    DCS::OctetSeq &_tao_sequence
  );
TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_DCS_OctetSeq_H_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:54


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DCS::DCS_DataDiff &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DCS::DCS_DataDiff &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1228
#if defined (__ACE_INLINE__)
#include "DCS_DataC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */


