// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler v1.6a_p8 ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:381


#include "DCS_DataTypeSupportC.h"
#include "tao/CDR.h"
#include "tao/SystemException.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "DCS_DataTypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:73

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:60

// Traits specializations for DCS::DCS_DataDiffTypeSupport.

DCS::DCS_DataDiffTypeSupport_ptr
TAO::Objref_Traits<DCS::DCS_DataDiffTypeSupport>::duplicate (
    DCS::DCS_DataDiffTypeSupport_ptr p)
{
  return DCS::DCS_DataDiffTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<DCS::DCS_DataDiffTypeSupport>::release (
    DCS::DCS_DataDiffTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

DCS::DCS_DataDiffTypeSupport_ptr
TAO::Objref_Traits<DCS::DCS_DataDiffTypeSupport>::nil (void)
{
  return DCS::DCS_DataDiffTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<DCS::DCS_DataDiffTypeSupport>::marshal (
    const DCS::DCS_DataDiffTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

DCS::DCS_DataDiffTypeSupport::DCS_DataDiffTypeSupport (void)
{}

DCS::DCS_DataDiffTypeSupport::~DCS_DataDiffTypeSupport (void)
{}

DCS::DCS_DataDiffTypeSupport_ptr
DCS::DCS_DataDiffTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return DCS_DataDiffTypeSupport::_duplicate (
      dynamic_cast<DCS_DataDiffTypeSupport_ptr> (_tao_objref)
    );
}

DCS::DCS_DataDiffTypeSupport_ptr
DCS::DCS_DataDiffTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return DCS_DataDiffTypeSupport::_duplicate (
      dynamic_cast<DCS_DataDiffTypeSupport_ptr> (_tao_objref)
    );
}

DCS::DCS_DataDiffTypeSupport_ptr
DCS::DCS_DataDiffTypeSupport::_duplicate (DCS_DataDiffTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

void
DCS::DCS_DataDiffTypeSupport::_tao_release (DCS_DataDiffTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
DCS::DCS_DataDiffTypeSupport::_is_a (const char *value)
{
  if (
      !ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:DCS/DCS_DataDiffTypeSupport:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* DCS::DCS_DataDiffTypeSupport::_interface_repository_id (void) const
{
  return "IDL:DCS/DCS_DataDiffTypeSupport:1.0";
}

::CORBA::Boolean
DCS::DCS_DataDiffTypeSupport::marshal (TAO_OutputCDR &)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:60

// Traits specializations for DCS::DCS_DataDiffDataWriter.

DCS::DCS_DataDiffDataWriter_ptr
TAO::Objref_Traits<DCS::DCS_DataDiffDataWriter>::duplicate (
    DCS::DCS_DataDiffDataWriter_ptr p)
{
  return DCS::DCS_DataDiffDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<DCS::DCS_DataDiffDataWriter>::release (
    DCS::DCS_DataDiffDataWriter_ptr p)
{
  ::CORBA::release (p);
}

DCS::DCS_DataDiffDataWriter_ptr
TAO::Objref_Traits<DCS::DCS_DataDiffDataWriter>::nil (void)
{
  return DCS::DCS_DataDiffDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<DCS::DCS_DataDiffDataWriter>::marshal (
    const DCS::DCS_DataDiffDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

DCS::DCS_DataDiffDataWriter::DCS_DataDiffDataWriter (void)
{}

DCS::DCS_DataDiffDataWriter::~DCS_DataDiffDataWriter (void)
{}

DCS::DCS_DataDiffDataWriter_ptr
DCS::DCS_DataDiffDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return DCS_DataDiffDataWriter::_duplicate (
      dynamic_cast<DCS_DataDiffDataWriter_ptr> (_tao_objref)
    );
}

DCS::DCS_DataDiffDataWriter_ptr
DCS::DCS_DataDiffDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return DCS_DataDiffDataWriter::_duplicate (
      dynamic_cast<DCS_DataDiffDataWriter_ptr> (_tao_objref)
    );
}

DCS::DCS_DataDiffDataWriter_ptr
DCS::DCS_DataDiffDataWriter::_duplicate (DCS_DataDiffDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

void
DCS::DCS_DataDiffDataWriter::_tao_release (DCS_DataDiffDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
DCS::DCS_DataDiffDataWriter::_is_a (const char *value)
{
  if (
      !ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:DCS/DCS_DataDiffDataWriter:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* DCS::DCS_DataDiffDataWriter::_interface_repository_id (void) const
{
  return "IDL:DCS/DCS_DataDiffDataWriter:1.0";
}

::CORBA::Boolean
DCS::DCS_DataDiffDataWriter::marshal (TAO_OutputCDR &)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:60

// Traits specializations for DCS::DCS_DataDiffDataReader.

DCS::DCS_DataDiffDataReader_ptr
TAO::Objref_Traits<DCS::DCS_DataDiffDataReader>::duplicate (
    DCS::DCS_DataDiffDataReader_ptr p)
{
  return DCS::DCS_DataDiffDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<DCS::DCS_DataDiffDataReader>::release (
    DCS::DCS_DataDiffDataReader_ptr p)
{
  ::CORBA::release (p);
}

DCS::DCS_DataDiffDataReader_ptr
TAO::Objref_Traits<DCS::DCS_DataDiffDataReader>::nil (void)
{
  return DCS::DCS_DataDiffDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<DCS::DCS_DataDiffDataReader>::marshal (
    const DCS::DCS_DataDiffDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

DCS::DCS_DataDiffDataReader::DCS_DataDiffDataReader (void)
{}

DCS::DCS_DataDiffDataReader::~DCS_DataDiffDataReader (void)
{}

DCS::DCS_DataDiffDataReader_ptr
DCS::DCS_DataDiffDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return DCS_DataDiffDataReader::_duplicate (
      dynamic_cast<DCS_DataDiffDataReader_ptr> (_tao_objref)
    );
}

DCS::DCS_DataDiffDataReader_ptr
DCS::DCS_DataDiffDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return DCS_DataDiffDataReader::_duplicate (
      dynamic_cast<DCS_DataDiffDataReader_ptr> (_tao_objref)
    );
}

DCS::DCS_DataDiffDataReader_ptr
DCS::DCS_DataDiffDataReader::_duplicate (DCS_DataDiffDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

void
DCS::DCS_DataDiffDataReader::_tao_release (DCS_DataDiffDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
DCS::DCS_DataDiffDataReader::_is_a (const char *value)
{
  if (
      !ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:DCS/DCS_DataDiffDataReader:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* DCS::DCS_DataDiffDataReader::_interface_repository_id (void) const
{
  return "IDL:DCS/DCS_DataDiffDataReader:1.0";
}

::CORBA::Boolean
DCS::DCS_DataDiffDataReader::marshal (TAO_OutputCDR &)
{
  return false;
}

